# 1. Importações

In [104]:
import pandas as pd
import numpy as np

# 2. Carregamento dos Dados

In [128]:
df_pedidos = pd.read_csv('dataset/pedidos.csv')

# 3. EDA

In [140]:
df_pedidos.head()

,ID_Pedido,Data,Cliente_ID,Item,Quantidade,Preco_Unitario,Receita_Item
0,1,2023-11-16,222,Torta de Limao,23.0,12.93,297.39
1,2,2024-05-25,232,Esfiha,NaN,5.87,NaN
2,3,2024-12-20,276,Wrap de Frango,7.0,25.98,181.86
3,4,2024-10-17,198,Batata Frita,NaN,11.62,NaN
4,5,2023-07-06,385,Esfiha,17.0,6.94,117.98

In [141]:
df_pedidos.tail()

,ID_Pedido,Data,Cliente_ID,Item,Quantidade,Preco_Unitario,Receita_Item
445,446,2024-02-27,360,Salada Caesar,30.0,27.35,820.50
446,447,2025-05-29,228,Salada Caesar,24.0,29.40,705.60
447,448,2025-08-23,243,Agua Mineral,26.0,4.54,118.04
448,449,2024-08-30,191,Pizza Calabresa,9.0,45.85,412.65
449,450,2025-09-29,122,Yakisoba,8.0,31.72,253.76

In [142]:
df_pedidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       450 non-null    int64
 1   Data            450 non-null    object
 2   Cliente_ID      450 non-null    int64
 3   Item            450 non-null    object
 4   Quantidade      431 non-null    float64
 5   Preco_Unitario  430 non-null    float64
 6   Receita_Item    412 non-null    float64
dtypes: float64(3), int64(2), object(2)
memory usage: 24.7+ KB

In [143]:
df_pedidos.describe()

        ID_Pedido  Cliente_ID  Quantidade  Preco_Unitario  Receita_Item
count  450.000000  450.000000  431.000000      430.000000    412.000000
mean   225.500000  245.864444   15.902552       17.856581    286.364879
std    130.048068   88.360604    9.087931       11.601652    270.865944
min      1.000000  100.000000    1.000000        4.090000      4.170000
25%    113.250000  169.000000    8.000000        8.920000     94.050000
50%    225.500000  241.500000   16.000000       13.095000    191.590000
75%    337.750000  325.750000   24.000000       27.402500    391.800000
max    450.000000  399.000000   30.000000       46.070000   1289.960000

In [144]:
df_pedidos.columns

Index(['ID_Pedido', 'Data', 'Cliente_ID', 'Item', 'Quantidade',
       'Preco_Unitario', 'Receita_Item'],
      dtype='object')

In [145]:
df_pedidos.isnull().sum()

ID_Pedido          0
Data               0
Cliente_ID         0
Item               0
Quantidade        19
Preco_Unitario    20
Receita_Item      38
dtype: int64

In [146]:
df_pedidos.duplicated().sum()

np.int64(0)

# 4. Feature Engineering

In [147]:
df_pedidos['Receita_Item'] = df_pedidos['Quantidade'] * df_pedidos['Preco_Unitario']

In [148]:
df_pedidos['Receita_Item'].isnull().sum()

np.int64(38)

# 5. Tratamento de Dados

In [149]:
df_pedidos.isnull().sum()

ID_Pedido          0
Data               0
Cliente_ID         0
Item               0
Quantidade        19
Preco_Unitario    20
Receita_Item      38
dtype: int64

In [151]:
df_pedidos_tratado = df_pedidos.copy()

df_pedidos_tratado['Quantidade'] = df_pedidos_tratado['Quantidade'].fillna(df_pedidos_tratado['Quantidade'].mean())

In [160]:
df_pedidos_tratado = df_pedidos_tratado.dropna(subset=['Preco_Unitario'])

In [163]:
df_pedidos_tratado.isnull().sum()

ID_Pedido         0
Data              0
Cliente_ID        0
Item              0
Quantidade        0
Preco_Unitario    0
Receita_Item      0
dtype: int64

In [162]:
df_pedidos_tratado['Receita_Item'] = df_pedidos_tratado['Quantidade'] * df_pedidos_tratado['Preco_Unitario']

C:\Users\Samsung\AppData\Local\Temp\ipykernel_17696\618185632.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pedidos_tratado['Receita_Item'] = df_pedidos_tratado['Quantidade'] * df_pedidos_tratado['Preco_Unitario']

# 6. Agregações

In [164]:
df_pedidos_tratado.columns

Index(['ID_Pedido', 'Data', 'Cliente_ID', 'Item', 'Quantidade',
       'Preco_Unitario', 'Receita_Item'],
      dtype='object')

In [175]:
df_pedidos_tratado['Quantidade'] = df_pedidos_tratado['Quantidade'].astype(int)

C:\Users\Samsung\AppData\Local\Temp\ipykernel_17696\1961784908.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pedidos_tratado['Quantidade'] = df_pedidos_tratado['Quantidade'].astype(int)

In [176]:
df_pedidos_tratado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 430 entries, 0 to 449
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       430 non-null    int64
 1   Data            430 non-null    object
 2   Cliente_ID      430 non-null    int64
 3   Item            430 non-null    object
 4   Quantidade      430 non-null    int64
 5   Preco_Unitario  430 non-null    float64
 6   Receita_Item    430 non-null    float64
dtypes: float64(2), int64(3), object(2)
memory usage: 26.9+ KB

In [177]:
quantidade_por_item = df_pedidos_tratado.groupby('Item')['Quantidade'].sum().reset_index()

quantidade_por_item

                   Item  Quantidade
0            Acai 300ml         402
1          Agua Mineral         327
2          Batata Frita         323
3               Brownie         465
4         Cafe Expresso         392
5              Empanada         321
6                Esfiha         362
7            Hamburguer         509
8                Pastel         238
9       Pizza Calabresa         371
10      Pizza Mussarela         349
11    Refrigerante Lata         343
12        Salada Caesar         352
13  Smoothie de Morango         325
14      Sorvete 2 bolas         284
15      Suco de Laranja         262
16        Sushi 8 pecas         378
17       Torta de Limao         248
18       Wrap de Frango         248
19             Yakisoba         318

In [182]:
receita_total_item = df_pedidos_tratado.groupby('Item')['Receita_Item'].sum().reset_index().rename(columns={'Receita_Item': 'Faturamento_Total'})
receita_total_item['Faturamento_Total'] = receita_total_item['Faturamento_Total'].round(2)
receita_total_item

                   Item  Faturamento_Total
0            Acai 300ml            6502.13
1          Agua Mineral            1469.40
2          Batata Frita            3970.36
3               Brownie            4603.50
4         Cafe Expresso            2657.71
5              Empanada            2893.26
6                Esfiha            2379.66
7            Hamburguer           11562.23
8                Pastel            2215.46
9       Pizza Calabresa           15903.65
10      Pizza Mussarela           14148.69
11    Refrigerante Lata            2606.87
12        Salada Caesar            9927.96
13  Smoothie de Morango            4745.44
14      Sorvete 2 bolas            3137.76
15      Suco de Laranja            2412.53
16        Sushi 8 pecas           12085.16
17       Torta de Limao            3305.11
18       Wrap de Frango            6611.08
19             Yakisoba            9514.64

In [191]:
quantidade_por_item.sort_values(by='Quantidade', ascending=False).head(5)

             Item  Quantidade
7      Hamburguer         509
3         Brownie         465
0      Acai 300ml         402
4   Cafe Expresso         392
16  Sushi 8 pecas         378

In [195]:
receita_total_item.sort_values(by='Faturamento_Total', ascending=False).head()

               Item  Faturamento_Total
9   Pizza Calabresa           15903.65
10  Pizza Mussarela           14148.69
16    Sushi 8 pecas           12085.16
7        Hamburguer           11562.23
12    Salada Caesar            9927.96

# 7. Análise Temporal

In [196]:
df_pedidos_tratado.columns

Index(['ID_Pedido', 'Data', 'Cliente_ID', 'Item', 'Quantidade',
       'Preco_Unitario', 'Receita_Item'],
      dtype='object')

In [198]:
df_pedidos_tratado['Data'] = pd.to_datetime(df_pedidos_tratado['Data'], errors='coerce')

C:\Users\Samsung\AppData\Local\Temp\ipykernel_17696\2486715192.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pedidos_tratado['Data'] = pd.to_datetime(df_pedidos_tratado['Data'], errors='coerce')

In [199]:
df_pedidos_tratado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 430 entries, 0 to 449
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       430 non-null    int64
 1   Data            430 non-null    datetime64[ns]
 2   Cliente_ID      430 non-null    int64
 3   Item            430 non-null    object
 4   Quantidade      430 non-null    int64
 5   Preco_Unitario  430 non-null    float64
 6   Receita_Item    430 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(1)
memory usage: 26.9+ KB

In [200]:
df_pedidos_tratado['Mes'] = df_pedidos_tratado['Data'].dt.month

C:\Users\Samsung\AppData\Local\Temp\ipykernel_17696\1251684996.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pedidos_tratado['Mes'] = df_pedidos_tratado['Data'].dt.month

In [201]:
df_pedidos_tratado.head()

,ID_Pedido,Data,Cliente_ID,Item,Quantidade,Preco_Unitario,Receita_Item,Mes
0,1,2023-11-16,222,Torta de Limao,23,12.93,297.390000,11
1,2,2024-05-25,232,Esfiha,15,5.87,93.347981,5
2,3,2024-12-20,276,Wrap de Frango,7,25.98,181.860000,12
3,4,2024-10-17,198,Batata Frita,15,11.62,184.787657,10
4,5,2023-07-06,385,Esfiha,17,6.94,117.980000,7

In [203]:
receita_por_mes = df_pedidos_tratado.groupby('Mes')['Receita_Item'].sum().reset_index()

receita_por_mes

    Mes  Receita_Item
0     1  10102.202668
1     2  16011.540000
2     3   7983.080000
3     4   8549.233503
4     5  12041.371067
5     6   9261.508863
6     7  10592.674084
7     8  12943.373503
8     9  14680.497517
9    10   5405.276984
10   11   6901.480000
11   12   8180.353341

In [207]:
evolucao_vendas_tempo = df_pedidos_tratado.sort_values('Data').groupby('Data')['Receita_Item'].sum().reset_index()

# 8. Merge

In [208]:
df_cardapio = pd.read_csv('./dataset/cardapio.csv')

df_cardapio.head()

              Item  Categoria  Preco_Base
0       Hamburguer   Salgados        22.9
1     Batata Frita   Salgados        12.5
2  Pizza Mussarela   Salgados        39.9
3  Pizza Calabresa   Salgados        42.9
4    Salada Caesar  Saudaveis        28.0

In [209]:
df_cardapio.tail()

               Item Categoria  Preco_Base
15         Yakisoba  Oriental        29.9
16  Sorvete 2 bolas     Doces        10.9
17           Esfiha  Salgados         6.5
18           Pastel  Salgados         9.5
19         Empanada  Salgados         8.9

In [210]:
df_cardapio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Item        20 non-null     object
 1   Categoria   20 non-null     object
 2   Preco_Base  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

In [211]:
df_cardapio.describe()

       Preco_Base
count   20.000000
mean    17.570000
std     11.708211
min      4.500000
25%      8.900000
50%     12.700000
75%     26.875000
max     42.900000

In [214]:
df_pedidos_tratado['Item'].nunique()

20

In [216]:
df_merge = pd.merge(df_pedidos_tratado, df_cardapio, how='left')

In [217]:
df_merge.columns

Index(['ID_Pedido', 'Data', 'Cliente_ID', 'Item', 'Quantidade',
       'Preco_Unitario', 'Receita_Item', 'Mes', 'Categoria', 'Preco_Base'],
      dtype='object')

In [218]:
receita_total_categoria = df_merge.groupby('Categoria')['Receita_Item'].sum().reset_index()

receita_total_categoria

   Categoria  Receita_Item
0    Bebidas   9146.506798
1      Doces  22293.944060
2   Oriental  21599.796473
3   Salgados  53073.304200
4  Saudaveis  16539.040000

In [231]:
index_categoria_maior_receita = receita_total_categoria['Receita_Item'].idxmax()

print(f'A categoria com maior receita é: {receita_total_categoria['Categoria'][index_categoria_maior_receita]}')

A categoria com maior receita é: Salgados

# 9. Filtros

In [232]:
df_merge.head()

,ID_Pedido,Data,Cliente_ID,Item,Quantidade,Preco_Unitario,Receita_Item,Mes,Categoria,Preco_Base
0,1,2023-11-16,222,Torta de Limao,23,12.93,297.390000,11,Doces,12.9
1,2,2024-05-25,232,Esfiha,15,5.87,93.347981,5,Salgados,6.5
2,3,2024-12-20,276,Wrap de Frango,7,25.98,181.860000,12,Saudaveis,26.5
3,4,2024-10-17,198,Batata Frita,15,11.62,184.787657,10,Salgados,12.5
4,5,2023-07-06,385,Esfiha,17,6.94,117.980000,7,Salgados,6.5

In [237]:
salgados_grande_quantidade = df_merge[(df_merge['Categoria'] == 'Salgados') & (df_merge['Quantidade'] > 10)]

salgados_grande_quantidade

,ID_Pedido,Data,Cliente_ID,Item,Quantidade,Preco_Unitario,Receita_Item,Mes,Categoria,Preco_Base
1,2,2024-05-25,232,Esfiha,15,5.87,93.347981,5,Salgados,6.5
3,4,2024-10-17,198,Batata Frita,15,11.62,184.787657,10,Salgados,12.5
4,5,2023-07-06,385,Esfiha,17,6.94,117.980000,7,Salgados,6.5
5,6,2023-02-04,260,Empanada,16,9.48,151.680000,2,Salgados,8.9
14,15,2023-02-03,103,Batata Frita,14,13.13,183.820000,2,Salgados,12.5
...,...,...,...,...,...,...,...,...,...,...
404,423,2023-02-05,252,Pizza Calabresa,16,41.75,668.000000,2,Salgados,42.9
409,428,2023-07-11,278,Pastel,18,9.30,167.400000,7,Salgados,9.5
415,434,2024-07-17,249,Esfiha,26,5.96,154.960000,7,Salgados,6.5
422,442,2023-01-02,261,Esfiha,15,6.83,108.614432,1,Salgados,6.5
424,444,2024-04-16,133,Esfiha,27,6.50,175.500000,4,Salgados,6.5

# 10. KPIs

In [238]:
df_merge.columns

Index(['ID_Pedido', 'Data', 'Cliente_ID', 'Item', 'Quantidade',
       'Preco_Unitario', 'Receita_Item', 'Mes', 'Categoria', 'Preco_Base'],
      dtype='object')

In [239]:
receita_total = df_merge['Receita_Item'].sum()
print(f'A receita total gerada foi: R${receita_total:.2f}')

A receita total gerada foi: R$122652.59

In [240]:
total_itens_vendidos = df_merge['Quantidade'].sum()
print(f'A quantidade total de itens vendidos foi: {total_itens_vendidos}')

A quantidade total de itens vendidos foi: 6817

In [243]:
ticket_medio = receita_total / df_merge['ID_Pedido'].nunique()
print(f'O ticket médio foi: R${ticket_medio:.2f}')

O ticket médio foi: R$285.24

In [249]:
q1_preco, q2_preco, q3_preco = np.percentile(df_merge['Preco_Unitario'], [25, 50, 75])

print(f'25% preço: {q1_preco}')
print(f'50% preço: {q2_preco}')
print(f'75% preço: {q3_preco}')

25% preço: 8.92
50% preço: 13.095
75% preço: 27.402500000000003

In [250]:
q1_qtd, q2_qtd, q3_qtd = np.percentile(df_merge['Quantidade'], [25,50,75])

print(f'25% quantidade: {q1_qtd}')
print(f'50% quantidade: {q2_qtd}')
print(f'75% quantidade: {q3_qtd}')

25% quantidade: 8.0
50% quantidade: 16.0
75% quantidade: 24.0

In [251]:
df_merge.describe()

,ID_Pedido,Data,Cliente_ID,Quantidade,Preco_Unitario,Receita_Item,Mes,Preco_Base
count,430.000000,430,430.000000,430.000000,430.000000,430.000000,430.000000,430.000000
mean,225.783721,2024-04-20 22:59:43.255813888,245.658140,15.853488,17.856581,285.238585,6.225581,17.805581
min,1.000000,2023-01-02 00:00:00,100.000000,1.000000,4.090000,4.170000,1.000000,4.500000
25%,112.250000,2023-08-05 06:00:00,169.000000,8.000000,8.920000,95.845000,3.000000,8.900000
50%,229.500000,2024-05-03 00:00:00,242.500000,16.000000,13.095000,191.590000,6.000000,12.900000
75%,338.750000,2024-12-09 12:00:00,325.750000,24.000000,27.402500,382.350000,9.000000,28.000000
max,450.000000,2025-09-29 00:00:00,399.000000,30.000000,46.070000,1289.960000,12.000000,42.900000
std,130.648097,NaN,88.569133,8.945284,11.601652,267.871057,3.318072,11.507057